[package]
name = "game-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
# protocol is headless, we dont want the bevy rendering/window system, its useless here
avian3d = { version = "0.7.0", default-features = false }
bevy = { version = "0.19.0", default-features = false }
lightyear = "0.28.0"
serde = "1.0.229"
